import { Project, Task, Client, Invoice, TimeEntry, Deliverable } from './types';

export const mockClients: Client[] = [
  {
    id: 'cli-1',
    name: 'Elena Rostova',
    company: 'Apex Design Labs',
    email: 'elena@apexdesign.io',
    phone: '+1 (555) 392-8812',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    billingAddress: '550 Howard St, Suite 400, San Francisco, CA 94105',
    defaultHourlyRate: 150,
    currency: 'USD',
    activeProjectsCount: 2,
    totalBilled: 24500,
    outstandingBalance: 4850,
    portalToken: 'portal_apex_89x2q1',
    notes: 'Key retainer client. Approves deliverables on Tuesdays.',
  },
  {
    id: 'cli-2',
    name: 'David Sterling',
    company: 'Vanguard Ventures',
    email: 'dsterling@vanguardvc.com',
    phone: '+1 (555) 714-9920',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    billingAddress: '100 Wall Street, Floor 28, New York, NY 10005',
    defaultHourlyRate: 175,
    currency: 'USD',
    activeProjectsCount: 1,
    totalBilled: 18200,
    outstandingBalance: 3200,
    portalToken: 'portal_vanguard_44k8z9',
    notes: 'Seed-stage VC portfolio branding and dashboard UI.',
  },
  {
    id: 'cli-3',
    name: 'Sophia Laurent',
    company: 'Monolith Studio Paris',
    email: 'sophia@monolith.fr',
    phone: '+33 1 42 68 55 00',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    billingAddress: '14 Rue du Faubourg Saint-Honoré, 75008 Paris',
    defaultHourlyRate: 140,
    currency: 'EUR',
    activeProjectsCount: 1,
    totalBilled: 31000,
    outstandingBalance: 0,
    portalToken: 'portal_monolith_12p7w4',
    notes: 'Luxury fashion e-commerce headless web app.',
  },
];

export const mockProjects: Project[] = [
  {
    id: 'proj-1',
    title: 'Apex OS - Design System & UI Kit',
    clientId: 'cli-1',
    clientName: 'Apex Design Labs',
    description: 'Comprehensive Figma & React Liquid Glass component design system for next-gen agency tools.',
    status: 'active',
    budget: 18000,
    hourlyRate: 150,
    deadline: '2026-10-15',
    accentColor: '#6366f1', // Indigo
    totalTasks: 14,
    completedTasks: 9,
    trackedHours: 42.5,
    billedAmount: 6375,
  },
  {
    id: 'proj-2',
    title: 'Vanguard Portfolio Investor Portal',
    clientId: 'cli-2',
    clientName: 'Vanguard Ventures',
    description: 'Real-time fund metrics, cap table viewer, and deal flow pipeline for LP investors.',
    status: 'active',
    budget: 25000,
    hourlyRate: 175,
    deadline: '2026-10-30',
    accentColor: '#06b6d4', // Cyan
    totalTasks: 20,
    completedTasks: 12,
    trackedHours: 58.0,
    billedAmount: 10150,
  },
  {
    id: 'proj-3',
    title: 'Monolith Headless E-Commerce Experience',
    clientId: 'cli-3',
    clientName: 'Monolith Studio Paris',
    description: 'Next.js 15 & Shopify Storefront API implementation with 60fps micro-interactions.',
    status: 'in_review',
    budget: 32000,
    hourlyRate: 140,
    deadline: '2026-09-28',
    accentColor: '#ec4899', // Pink
    totalTasks: 18,
    completedTasks: 17,
    trackedHours: 95.0,
    billedAmount: 13300,
  },
];

export const mockTasks: Task[] = [
  {
    id: 'task-1',
    projectId: 'proj-1',
    title: 'Figma Token Sync & OKLCH Theme Architecture',
    description: 'Establish specular glass shine borders, Gaussian blur values, and dynamic light/dark tokens.',
    status: 'in_progress',
    priority: 'urgent',
    orderIndex: 0,
    dueDate: '2026-09-20',
    estimatedMinutes: 240,
    trackedMinutes: 180,
    tags: ['Design System', 'Tokens'],
    assignedTo: {
      name: 'Alex Vance',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    },
  },
  {
    id: 'task-2',
    projectId: 'proj-1',
    title: 'Floating Pill Sidebar Dual-State Spring Animation',
    description: 'Build 72px compact dock and 240px expanded drawer with Framer Motion spring physics.',
    status: 'in_progress',
    priority: 'high',
    orderIndex: 1,
    dueDate: '2026-09-21',
    estimatedMinutes: 180,
    trackedMinutes: 120,
    tags: ['Frontend', 'Animation'],
    assignedTo: {
      name: 'Julian Reed',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    },
  },
  {
    id: 'task-3',
    projectId: 'proj-1',
    title: 'Horizontal Liquid Glass Calendar Bar Header',
    description: 'Implement 30-day date strip with horizontal inertia scroll and glowing active day pill.',
    status: 'backlog',
    priority: 'high',
    orderIndex: 0,
    dueDate: '2026-09-23',
    estimatedMinutes: 200,
    trackedMinutes: 0,
    tags: ['UI Component', 'Calendar'],
  },
  {
    id: 'task-4',
    projectId: 'proj-1',
    title: 'Tokenized Zero-Friction Client Portal Routing',
    description: 'Create crypto timing-safe lookup for client magic links with deliverable feedback.',
    status: 'in_review',
    priority: 'medium',
    orderIndex: 0,
    dueDate: '2026-09-19',
    estimatedMinutes: 300,
    trackedMinutes: 290,
    tags: ['Security', 'Portals'],
  },
  {
    id: 'task-5',
    projectId: 'proj-1',
    title: 'Invoice Itemizer Auto-Convert from Time Logs',
    description: 'One-click bridge to convert unbilled time entries into line items with tax calculations.',
    status: 'done',
    priority: 'urgent',
    orderIndex: 0,
    dueDate: '2026-09-18',
    estimatedMinutes: 150,
    trackedMinutes: 145,
    tags: ['Invoicing', 'Finance'],
  },
  {
    id: 'task-6',
    projectId: 'proj-2',
    title: 'Stripe Connect Webhook & Instant Receipt Generation',
    description: 'Automated invoice status transition from Sent to Paid upon checkout.session.completed.',
    status: 'done',
    priority: 'high',
    orderIndex: 1,
    dueDate: '2026-09-17',
    estimatedMinutes: 210,
    trackedMinutes: 210,
    tags: ['Stripe', 'Backend'],
  },
];

export const mockTimeEntries: TimeEntry[] = [
  {
    id: 'time-1',
    projectId: 'proj-1',
    projectName: 'Apex OS - Design System',
    clientId: 'cli-1',
    clientName: 'Apex Design Labs',
    taskId: 'task-1',
    taskTitle: 'Figma Token Sync & OKLCH Theme Architecture',
    description: 'Configured specular glass borders and Gaussian blur token presets.',
    startTime: '2026-09-18T09:00:00Z',
    endTime: '2026-09-18T12:00:00Z',
    durationSeconds: 10800, // 3.0 hrs
    hourlyRate: 150,
    isBillable: true,
    isBilled: false,
  },
  {
    id: 'time-2',
    projectId: 'proj-1',
    projectName: 'Apex OS - Design System',
    clientId: 'cli-1',
    clientName: 'Apex Design Labs',
    taskId: 'task-2',
    taskTitle: 'Floating Pill Sidebar Dual-State Spring Animation',
    description: 'Engineered smooth spring physics and hover tooltip bubble mechanics.',
    startTime: '2026-09-18T13:30:00Z',
    endTime: '2026-09-18T15:30:00Z',
    durationSeconds: 7200, // 2.0 hrs
    hourlyRate: 150,
    isBillable: true,
    isBilled: false,
  },
  {
    id: 'time-3',
    projectId: 'proj-2',
    projectName: 'Vanguard Portfolio Investor Portal',
    clientId: 'cli-2',
    clientName: 'Vanguard Ventures',
    taskId: 'task-6',
    taskTitle: 'Stripe Connect Webhook & Instant Receipt Generation',
    description: 'Configured webhook verification secret and automatic status polling.',
    startTime: '2026-09-17T10:00:00Z',
    endTime: '2026-09-17T13:30:00Z',
    durationSeconds: 12600, // 3.5 hrs
    hourlyRate: 175,
    isBillable: true,
    isBilled: true,
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: 'inv-101',
    invoiceNumber: 'INV-2026-0042',
    clientId: 'cli-1',
    clientName: 'Elena Rostova',
    clientCompany: 'Apex Design Labs',
    clientEmail: 'elena@apexdesign.io',
    status: 'sent',
    issueDate: '2026-09-15',
    dueDate: '2026-09-30',
    currency: 'USD',
    subtotal: 4500,
    taxRate: 7.5,
    taxAmount: 337.5,
    totalAmount: 4837.5,
    notes: 'Thank you for partnering with us. Payment terms: Net 15 via Stripe or Wire.',
    stripePaymentUrl: 'https://checkout.stripe.com/pay/cs_live_apex_inv42',
    items: [
      {
        id: 'item-1',
        description: 'Sprint 1 - Liquid Glass Navigation & Token System',
        quantity: 20,
        unitPrice: 150,
        amount: 3000,
      },
      {
        id: 'item-2',
        description: 'Sprint 2 - Ambient Floating Timer & Live Store',
        quantity: 10,
        unitPrice: 150,
        amount: 1500,
      },
    ],
  },
  {
    id: 'inv-102',
    invoiceNumber: 'INV-2026-0041',
    clientId: 'cli-2',
    clientName: 'David Sterling',
    clientCompany: 'Vanguard Ventures',
    clientEmail: 'dsterling@vanguardvc.com',
    status: 'paid',
    issueDate: '2026-09-01',
    dueDate: '2026-09-15',
    currency: 'USD',
    subtotal: 7000,
    taxRate: 0,
    taxAmount: 0,
    totalAmount: 7000,
    paidAt: '2026-09-12T14:22:00Z',
    notes: 'Fund metrics dashboard milestone completion payment.',
    items: [
      {
        id: 'item-3',
        description: 'Vanguard LP Portal Architecture & Setup',
        quantity: 40,
        unitPrice: 175,
        amount: 7000,
      },
    ],
  },
];

export const mockDeliverables: Deliverable[] = [
  {
    id: 'del-1',
    projectId: 'proj-1',
    title: 'Apex OS Liquid Glass Component Library (.fig)',
    description: 'Final production Figma component system with 48 variant states and token documentation.',
    fileType: 'figma',
    fileSize: '42.8 MB',
    status: 'approved',
    submittedAt: '2026-09-16T17:00:00Z',
    clientFeedback: 'Spectacular attention to Apple glass shaders and pill ergonomics. Approved!',
  },
  {
    id: 'del-2',
    projectId: 'proj-1',
    title: 'RuneyOS Navigation Dock Architecture Spec (PDF)',
    description: 'Comprehensive technical blueprint for dual-state sidebar and horizontal calendar strip.',
    fileType: 'pdf',
    fileSize: '3.4 MB',
    status: 'pending_approval',
    submittedAt: '2026-09-18T11:30:00Z',
  },
];
